export default {
  products: [
    {
      _id: '1',
      name: 'Suit',
      category: 'Suits',
      image: '/images/image1.jpg',
      price: 200,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      description: 'Pant suits for elegance Ladies',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    },
    {
      _id: '2',
      name: 'Ball Gown',
      category: 'Gowns',
      image: '/images/gown.jpg',
      price: 150,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      countInStock: 9,
      description: 'Ball gown for Ladies',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    },
    {
      _id: '3',
      name: 'Wedding Gown',
      category: 'Gowns',
      image: '/images/gown2.webp',
      price: 300,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      countInStock: 12,
      description: 'Memorable expreience is created for elegance Ladies',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    },
    {
      _id: '4',
      name: 'Smart Gown',
      category: 'Gowns',
      image: '/images/officegown.jpeg',
      price: 85,
      brand: 'Gucci',
      rating: 4.0,
      numReviews: 20,
      countInStock: 12,
      description: 'Brings out the boss Lady in you',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    },
    {
      _id: '5',
      name: 'Office Gown',
      category: 'Gowns',
      image: '/images/officegown2.jpeg',
      price: 85,
      brand: 'Gucci',
      rating: 4.0,
      numReviews: 20,
      countInStock: 9,
      description: 'Makes the official appearance like never before',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    },
    {
      _id: '6',
      name: 'Fit Skirt',
      category: 'Skirts',
      image: '/images/skirt.jpeg',
      price: 60,
      brand: 'Gucci',
      rating: 3.5,
      numReviews: 12,
      countInStock: 9,
      description: 'Perfect feminine look',
      reviews: [{
        name: 'Jane',
        rating: 4,
        comment: 'Great',
      }],
    }],
};
